# App
spring.application.name=kivra

# Database
spring.datasource.url=jdbc:postgresql://ep-gentle-meadow-alv5rj84.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_KJWN2DnYy8GB
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=kivra_super_secret_key_che_deve_essere_lunga_almeno_256_bit_ok
jwt.expiration=86400000

# CORS
frontend.url=http://localhost:4200